"""Shared ROBIN contracts."""

from robin_contracts.canonical import (
    CanonicalizationError,
    canonical_json_bytes,
    sha256_v1,
)
from robin_contracts.cards import (
    BackendResampled,
    HeadCard,
    ModelCard,
    ModelRef,
    PadPolicy,
    Resampling,
    RunnerResampled,
    read_card,
    write_card,
)
from robin_contracts.inputs import AudioClip, Embeddings, Input
from robin_contracts.layout import artifact_path
from robin_contracts.output_contracts import (
    DetectionPolicy,
    DetectionsRequest,
    EmbeddingsRequest,
    OutputRequest,
    ScoresRequest,
    ThresholdPolicy,
    TopKPolicy,
)
from robin_contracts.protocols import (
    JsonScalar,
    Log,
    Model,
    ModelContext,
    ScoreRetention,
    noop,
)
from robin_contracts.records import ClassScore, WindowOutput
from robin_contracts.registry import RegistryEntry, TaxonRegistry
from robin_contracts.results import (
    RECORDING_FAILURE_STAGES,
    WORK_FAILURE_STAGES,
    ArtifactRecord,
    FailureReport,
    InferenceCompleted,
    InferenceFailure,
    InferenceResult,
    RecordingCoverage,
    RecordingFailed,
    ZeroWindowReason,
)
from robin_contracts.specs import (
    AudioSpec,
    Recipe,
    RecipeFingerprint,
    WindowGeometry,
    recipe,
    window_bounds,
    window_count,
)
from robin_contracts.work import (
    AudioInput,
    EmbeddingArtifactInput,
    InferenceWork,
    InputArtifact,
    PinnedFile,
    PinnedModel,
    RecordingRef,
    partition,
    recording_work_digest,
    work_digest,
)

__all__ = [
    "RECORDING_FAILURE_STAGES",
    "WORK_FAILURE_STAGES",
    "ArtifactRecord",
    "AudioClip",
    "AudioInput",
    "AudioSpec",
    "BackendResampled",
    "CanonicalizationError",
    "ClassScore",
    "DetectionPolicy",
    "DetectionsRequest",
    "EmbeddingArtifactInput",
    "Embeddings",
    "EmbeddingsRequest",
    "FailureReport",
    "HeadCard",
    "InferenceCompleted",
    "InferenceFailure",
    "InferenceResult",
    "InferenceWork",
    "Input",
    "InputArtifact",
    "JsonScalar",
    "Log",
    "Model",
    "ModelCard",
    "ModelContext",
    "ModelRef",
    "OutputRequest",
    "PadPolicy",
    "PinnedFile",
    "PinnedModel",
    "Recipe",
    "RecipeFingerprint",
    "RecordingCoverage",
    "RecordingFailed",
    "RecordingRef",
    "RegistryEntry",
    "Resampling",
    "RunnerResampled",
    "ScoreRetention",
    "ScoresRequest",
    "TaxonRegistry",
    "ThresholdPolicy",
    "TopKPolicy",
    "WindowGeometry",
    "WindowOutput",
    "ZeroWindowReason",
    "artifact_path",
    "canonical_json_bytes",
    "noop",
    "partition",
    "read_card",
    "recipe",
    "recording_work_digest",
    "sha256_v1",
    "window_bounds",
    "window_count",
    "work_digest",
    "write_card",
]
